version: "3.9"

services:
  web:
    image: php:7.4-apache
    container_name: apache_php
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www/html
    depends_on:
      - db

  db:
    image: mariadb:10.11
    container_name: mariadb-container
    environment:
      MARIADB_ROOT_PASSWORD: sup4rs3cure
      MARIADB_DATABASE: promocesi
      MARIADB_USER: johnny
      MARIADB_PASSWORD: s3cr4T
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
